
#ifdef MINIMIZE_GAME_FOOTPRINT
#define LCD_IMAGE_H 128
#define LCD_IMAGE_W 128
#else
#define LCD_IMAGE_H 320
#define LCD_IMAGE_W 240
#endif

#define LCD_FRAMEBUFFER_SEGMENTS 4
#define LCD_FRAMEBUFFER_W LCD_IMAGE_W
#define LCD_FRAMEBUFFER_H (LCD_IMAGE_H/LCD_FRAMEBUFFER_SEGMENTS)

#define LCD_IMAGE_PIXELS (LCD_IMAGE_W * LCD_IMAGE_H)
#define LCD_FRAMEBUFFER_PIXELS (LCD_FRAMEBUFFER_W * LCD_FRAMEBUFFER_H)

extern uint16_t lcd_framebuffer[LCD_FRAMEBUFFER_PIXELS];
extern int framebuffer_offset_h;

void lcd_flip();
void lcd_init();
