#pragma once

#define book_1_item 0
#define book_2_item 1
#define book_3_item 2
#define book_4_item 3
#define book_5_item 4
#define book_6_item 5
#define fish_grade_0_item 6
#define fish_grade_1_item 7
#define fish_grade_2_item 8
#define food_bagel_item 9
#define food_bananas_item 10
#define food_barley_tea_item 11
#define food_beef_noodles_item 12
#define food_bento_item 13
#define food_bread_item 14
#define food_burger_item 15
#define food_carrots_item 16
#define food_cigs_item 17
#define food_coffee_item 18
#define food_congee_item 19
#define food_curry_green_item 20
#define food_curry_red_item 21
#define food_donut_item 22
#define food_dumplings_item 23
#define food_egg_item 24
#define food_empanadas_item 25
#define food_green_tea_item 26
#define food_hotdog_item 27
#define food_milk_item 28
#define food_nasi_lemak_item 29
#define food_oranges_item 30
#define food_pad_ka_prow_item 31
#define food_persimmons_item 32
#define food_pill_foc_item 33
#define food_pill_spi_item 34
#define food_pill_vig_item 35
#define food_ramen_item 36
#define food_raw_meat_item 37
#define food_salad_item 38
#define food_salmon_item 39
#define food_sausage_item 40
#define food_soda_item 41
#define food_soup_item 42
#define food_strange_meal_item 43
#define food_tuna_item 44
#define mask_item 45
#define prop_bowl_gold_item 46
#define prop_bowl_grey_item 47
#define prop_bowl_mahogany_item 48
#define prop_bowl_stone_item 49
#define prop_bowl_walnut_item 50
#define prop_bush_daisy_item 51
#define prop_bush_lilac_item 52
#define prop_bush_plain_item 53
#define prop_chair_mahogany_item 54
#define prop_chair_plastic_item 55
#define prop_chair_stone_item 56
#define prop_chess_item 57
#define prop_chicken_item 58
#define prop_coffeemaker_item 59
#define prop_crystal_blue_item 60
#define prop_crystal_green_item 61
#define prop_crystal_purple_item 62
#define prop_effigy_blue_item 63
#define prop_effigy_purple_item 64
#define prop_effigy_sea_item 65
#define prop_crafter_item 66
#define prop_fan_classic_item 67
#define prop_fan_modern_item 68
#define prop_foc_flower_item 69
#define prop_lantern_item 70
#define prop_laptop_item 71
#define prop_mine_item 72
#define prop_padkaprow_item 73
#define prop_pixel_item 74
#define prop_plant_corn_item 75
#define prop_plant_daisy_item 76
#define prop_plant_lilac_item 77
#define prop_plant_maroon_item 78
#define prop_plant_plain_item 79
#define prop_purifier_item 80
#define prop_spi_flower_item 81
#define prop_stool_gold_item 82
#define prop_stool_plastic_item 83
#define prop_stool_stone_item 84
#define prop_stool_wood_item 85
#define prop_succulent_item 86
#define prop_table_mahogany_item 87
#define prop_table_plastic_item 88
#define prop_table_plastic_alt_item 89
#define prop_table_sm_mahogany_item 90
#define prop_table_sm_plastic_item 91
#define prop_table_sm_plastic_alt_item 92
#define prop_table_sm_walnut_item 93
#define prop_table_sm_walnut_alt_item 94
#define prop_table_walnut_item 95
#define prop_uv_lamp_item 96
#define prop_vase_gold_item 97
#define prop_vase_grey_item 98
#define prop_vase_mahogany_item 99
#define prop_vase_stone_item 100
#define prop_vase_walnut_item 101
#define prop_vig_flower_item 102
#define toy_baseball_item 103
#define toy_basketball_item 104
#define toy_duck_item 105
#define toy_golf_item 106
#define toy_laser_pointer_item 107
#define toy_puzzle_item 108
#define coin_item 109
#define prop_portal_orange_item 110
#define prop_portal_blue_item 111
#define prop_xen_crystal_item 112
#define prop_hoopy_item 113
#define save_migrate_mark_item 114
#define save_reset_mark_item 115
#define save_extend_mark_item 116
#define ingr_wood_item 117
#define ingr_stone_item 118
#define ingr_fibre_item 119
#define ingr_clay_item 120
#define ingr_seeds_item 121
#define ingr_oil_item 122
#define ingr_ink_item 123
#define ingr_water_item 124
#define ingr_time_item 125
#define ingr_aether_item 126
#define ingr_miasma_item 127
#define ingr_bone_item 128
#define ingr_ceramic_item 129
#define ingr_charcoal_item 130
#define ingr_cloth_item 131
#define ingr_glass_item 132
#define ingr_leather_item 133
#define ingr_paper_item 134
#define ingr_salt_item 135
#define ingr_sugar_item 136
#define ingr_sand_item 137
