#pragma once

#include "cat_sprite.h"

#define base_wall_sprite 0
#define sky_wall_sprite 1
#define base_floor_sprite 2
#define grass_floor_sprite 3
#define ash_floor_sprite 4
#define glyph_sprite 5
#define strike_sprite 6
#define icon_pointer_sprite 7
#define icon_a_sprite 8
#define icon_b_sprite 9
#define icon_n_sprite 10
#define icon_e_sprite 11
#define icon_s_sprite 12
#define icon_w_sprite 13
#define icon_start_sprite 14
#define icon_select_sprite 15
#define icon_enter_sprite 16
#define icon_exit_sprite 17
#define icon_plot_sprite 18
#define icon_equip_sprite 19
#define icon_input_sprite 20
#define icon_item_key_sprite 21
#define icon_item_food_sprite 22
#define icon_item_book_sprite 23
#define icon_item_toy_sprite 24
#define icon_item_prop_sprite 25
#define icon_item_gear_sprite 26
#define icon_coin_sprite 27
#define icon_vig_sprite 28
#define icon_foc_sprite 29
#define icon_spi_sprite 30
#define pip_vig_sprite 31
#define pip_foc_sprite 32
#define pip_spi_sprite 33
#define pip_empty_sprite 34
#define icon_temp_sprite 35
#define icon_co2_sprite 36
#define icon_pm_sprite 37
#define icon_voc_sprite 38
#define icon_nox_sprite 39
#define icon_mask_sprite 40
#define icon_pure_sprite 41
#define icon_uv_sprite 42
#define icon_nosmoke_sprite 43
#define icon_ee_sprite 44
#define icon_aq_ccode_sprite 45
#define icon_cell_sprite 46
#define icon_feed_sprite 47
#define icon_study_sprite 48
#define icon_play_sprite 49
#define icon_deco_sprite 50
#define icon_menu_sprite 51
#define cursor_sprite 52
#define tile_hl_sprite 53
#define cursor_add_sprite 54
#define tile_hl_add_sprite 55
#define cursor_flip_sprite 56
#define tile_hl_flip_sprite 57
#define tile_mark_flip_sprite 58
#define cursor_remove_sprite 59
#define tile_hl_rm_sprite 60
#define tile_mark_rm_sprite 61
#define button_hl_sprite 62
#define touch_hl_sprite 63
#define bread_sprite 64
#define coffee_sprite 65
#define milk_sprite 66
#define soup_sprite 67
#define salad_sprite 68
#define sausage_sprite 69
#define green_curry_sprite 70
#define red_curry_sprite 71
#define padkaprow_sprite 72
#define pill_vig_sprite 73
#define pill_foc_sprite 74
#define pill_spi_sprite 75
#define cigarette_sprite 76
#define book_static_sprite 77
#define book_study_sprite 78
#define toy_duck_sprite 79
#define toy_baseball_sprite 80
#define toy_basketball_sprite 81
#define toy_golf_sprite 82
#define toy_puzzle_sprite 83
#define coin_static_sprite 84
#define coin_world_sprite 85
#define window_dawn_sprite 86
#define window_morning_sprite 87
#define window_day_sprite 88
#define window_day_bad_aq_sprite 89
#define window_evening_sprite 90
#define window_dusk_sprite 91
#define window_night_sprite 92
#define vending_sprite 93
#define arcade_sprite 94
#define gpu_sprite 95
#define uv_sprite 96
#define purifier_sprite 97
#define coffeemaker_sprite 98
#define fan_a_sprite 99
#define fan_b_sprite 100
#define lantern_sprite 101
#define laptop_sprite 102
#define chess_sprite 103
#define table_mahogany_sprite 104
#define table_sm_mahogany_sprite 105
#define table_sm_plastic_sprite 106
#define table_sm_plastic_alt_sprite 107
#define table_sm_walnut_sprite 108
#define table_sm_walnut_alt_sprite 109
#define chair_mahogany_sprite 110
#define chair_stone_sprite 111
#define stool_wood_sprite 112
#define stool_stone_sprite 113
#define stool_gold_sprite 114
#define bowl_stone_sprite 115
#define bowl_gold_sprite 116
#define succulent_sprite 117
#define bush_plain_sprite 118
#define bush_daisy_sprite 119
#define bush_lilac_sprite 120
#define plant_plain_sprite 121
#define plant_maroon_sprite 122
#define plant_lilac_sprite 123
#define plant_daisy_sprite 124
#define flower_vig_sprite 125
#define flower_foc_sprite 126
#define flower_spi_sprite 127
#define crystal_blue_lg_sprite 128
#define crystal_green_lg_sprite 129
#define crystal_purple_lg_sprite 130
#define effigy_blue_sprite 131
#define effigy_purple_sprite 132
#define effigy_sea_sprite 133
#define poster_zk_sprite 134
#define pixel_sprite 135
#define padkaprop_sprite 136
#define pet_idle_sprite 137
#define pet_walk_sprite 138
#define pet_idle_high_vig_sprite 139
#define pet_walk_high_vig_sprite 140
#define pet_high_vig_in_sprite 141
#define pet_high_vig_out_sprite 142
#define pet_idle_high_foc_sprite 143
#define pet_walk_high_foc_sprite 144
#define pet_idle_high_spi_sprite 145
#define pet_walk_high_spi_sprite 146
#define pet_idle_low_vig_sprite 147
#define pet_walk_low_vig_sprite 148
#define pet_idle_low_foc_sprite 149
#define pet_walk_low_foc_sprite 150
#define pet_idle_low_spi_sprite 151
#define pet_walk_low_spi_sprite 152
#define pet_crit_vig_in_sprite 153
#define pet_crit_vig_sprite 154
#define pet_crit_vig_out_sprite 155
#define pet_crit_foc_in_sprite 156
#define pet_crit_foc_sprite 157
#define pet_crit_foc_out_sprite 158
#define pet_crit_spi_in_sprite 159
#define pet_crit_spi_sprite 160
#define pet_crit_spi_out_sprite 161
#define pet_eat_in_sprite 162
#define pet_eat_sprite 163
#define pet_eat_out_sprite 164
#define pet_study_in_sprite 165
#define pet_study_sprite 166
#define pet_study_out_sprite 167
#define pet_play_a_sprite 168
#define pet_play_b_sprite 169
#define pet_play_c_sprite 170
#define pet_vig_up_sprite 171
#define pet_foc_up_sprite 172
#define pet_spi_up_sprite 173
#define mood_low_vig_sprite 174
#define mood_low_foc_sprite 175
#define mood_low_spi_sprite 176
#define mood_good_sprite 177
#define mood_bad_sprite 178
#define snake_head_sprite 179
#define snake_body_sprite 180
#define snake_corner_sprite 181
#define snake_tail_sprite 182
#define bento_sprite 183
#define meat_sprite 184
#define orange_sprite 185
#define persimmons_sprite 186
#define soda_sprite 187
#define barley_tea_sprite 188
#define green_tea_sprite 189
#define tea_cup_sprite 190
#define tea_cup_empty_sprite 191
#define mines_sprite 192
#define fighter_sprite 193
#define bowl_grey_sprite 194
#define bowl_mahogany_sprite 195
#define bowl_walnut_sprite 196
#define chair_plastic_sprite 197
#define plant_corn_sprite 198
#define chicken_sprite 199
#define prop_mine_sprite 200
#define stool_plastic_sprite 201
#define table_plastic_sprite 202
#define table_plastic_alt_sprite 203
#define table_walnut_sprite 204
#define vase_gold_sprite 205
#define vase_grey_sprite 206
#define vase_mahogany_sprite 207
#define vase_stone_sprite 208
#define vase_walnut_sprite 209
#define icon_low_battery 210
#define icon_low_battery_alt 211
#define icon_low_battery_pet 212
#define null_sprite 213
