#pragma once

typedef enum CAT_button
{
    CAT_BUTTON_START,
    CAT_BUTTON_SELECT,
    CAT_BUTTON_A,
    CAT_BUTTON_B,
    CAT_BUTTON_DOWN,
    CAT_BUTTON_RIGHT,
    CAT_BUTTON_LEFT,
    CAT_BUTTON_UP,
    CAT_BUTTON_LAST
} CAT_button;