#!/opt/homebrew/bin/python3

import sys;

if(len(sys.argv) != 2):
	print("usage: soundgen.py <.bin path>");
	exit();
path = sys.argv[1];

data = [];
with open(path, "rb") as file:
	data = file.read();

with open("src/cat_sound_asset.h", "w") as file:
	prefix ="""// GENERATED BY SOUNDGEN.PY FROM {0}
#pragma once

#include <stdint.h>

struct
{{
	uint8_t samples[{1}];
}} sound =
{{""".format(path, len(data));
	file.write(prefix);

	file.write("""
	.samples =
	{\n""");

	new_line = True;
	for (idx, b) in enumerate(data):
		if new_line:
			file.write("\t\t");
			new_line = False;
		file.write(str(b));
		if idx != len(data)-1:
			file.write(',');
		if idx > 0 and idx % 32 == 0:
			file.write('\n');
			new_line = True;

	file.write("""
	}""");

	file.write("""
};
"""
	);